apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/izumi03460-git/k8s-manifests.git'
    targetRevision: HEAD
    path: apache-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
