apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-helm
spec:
  ingressClassName: nginx

  rules:
  - host: apache.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-helm
            port:
              number: 80
